hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  gen_batch_size: ${data.train_batch_size}

reward_model:
  reward_manager: dapo
  overlong_buffer: 
    enable: False # We try to avoid forgetting to set enable
    len: 0
    penalty_factor: 0.0
    log: False

algorithm:
  filter_groups:
    _target_: verl.trainer.config.FilterGroupsConfig
    enable: False # We try to avoid forgetting to set enable
    metric: null # acc / score / seq_reward / seq_final_reward / ...
    max_num_gen_batches: 0 # Non-positive values mean no upper limit
  custom_adv:
    use_delta_l: False
    delta_l_alpha: 1.0
    use_dual_agg: False
    dual_agg_batch_mean: False
    dual_agg_clip_factor: 2.0
    dual_agg_alpha: 1.0
    dual_agg_beta: 0.0
    dual_agg_use_harmonic_mean: False
    use_virtual_correct: False
  gfpo:
    gfpo_k: 8
  use_prompt_mean_adv: False
  filter_sample:
    enable: False
    metric: "response length"
    retain_count: 8
    adaptive: False
    easy_count: 8
    medium_count: 8
    hard_count: 8
    very_hard_count: 8

actor_rollout_ref:
  rollout:
    val_kwargs:
      response_length: ${data.max_response_length}

trainer:
  project_name: verl-dapo
